application:
  port: 8000
  base_url: "http://localhost"
database:
  host: "localhost"
  port: 5432
  username: "app"
  password: "secret"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my_secret_token"
  timeout_milliseconds: 100