application:
  port: 8000
  base_url: "http://localhost"
  hmac_secret: "super-long-secret-for-hmac-encryption-yes-really-super-long-yes-really-really-super-long"
database:
  host: "localhost"
  port: 5432
  username: "app"
  password: "secret"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "http://localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my_secret_token"
  timeout_milliseconds: 100
redis_uri: "redis://localhost:6379"